source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'pg'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'turbolinks'
gem 'httparty'
gem 'polylines'
gem 'nokogiri'
gem 'serviceable'
gem 'will_paginate'
gem 'haml'
gem 'responders'
gem 'delayed_job'
gem 'delayed_job_active_record'
